// Feedback Widget - Screenshot + GitHub Issues

const GITHUB_REPO = "social-engineer-ai/shopsaathi-feedback";
const GITHUB_TOKEN = "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";

function openFeedback() {
  const screenName = AppState.currentScreen || 'unknown';
  const role = AppState.role || 'unknown';

  showModal('💬 Feedback', `
    <div style="margin-bottom:12px;">
      <div class="info-row"><span class="info-label">Screen</span><span class="info-value">${screenName}</span></div>
      <div class="info-row"><span class="info-label">Role</span><span class="info-value">${role}</span></div>
    </div>

    ${FormDropdown('Feedback Type', 'fb-type', [
      { value: 'bug', label: '🐛 Bug / Issue' },
      { value: 'ui', label: '🎨 UI / Design' },
      { value: 'feature', label: '💡 Feature Request' },
      { value: 'text', label: '📝 Text / Translation' },
      { value: 'other', label: '📋 Other' }
    ])}

    ${FormTextarea('Comment', 'fb-comment', { placeholder: 'क्या बदलना चाहिए? What should change?', rows: 4 })}

    <div id="fb-screenshot-preview" style="margin:12px 0;"></div>

    <div class="modal-actions" style="flex-direction:column; gap:8px;">
      ${ActionButton('📸 Take Screenshot', 'captureScreenshot()', { type: 'secondary' })}
      ${ActionButton('📤 Submit Feedback', 'submitFeedback()', { type: 'primary' })}
    </div>

    <div style="font-size:11px; color:var(--gray-400); margin-top:12px; text-align:center;">
      Feedback will be saved as a GitHub Issue with screenshot
    </div>
  `);
}

function captureScreenshot() {
  // Check if html2canvas is available
  if (typeof html2canvas !== 'undefined') {
    const app = document.getElementById('app');
    // Hide modal temporarily for screenshot
    const modal = document.querySelector('.modal-overlay');
    if (modal) modal.style.display = 'none';

    html2canvas(app, {
      scale: 1,
      width: 420,
      useCORS: true,
      logging: false
    }).then(canvas => {
      if (modal) modal.style.display = '';
      const dataUrl = canvas.toDataURL('image/png');
      AppState.feedbackScreenshot = dataUrl;
      const preview = document.getElementById('fb-screenshot-preview');
      if (preview) {
        preview.innerHTML = `
          <div style="border:1px solid var(--gray-200); border-radius:8px; overflow:hidden;">
            <img src="${dataUrl}" style="width:100%; display:block;" alt="Screenshot">
          </div>
          <div style="text-align:center; font-size:12px; color:var(--green-dark); margin-top:4px;">✅ Screenshot captured</div>
        `;
      }
    }).catch(err => {
      if (modal) modal.style.display = '';
      showToast('Screenshot failed - continuing without it');
      console.error('Screenshot error:', err);
    });
  } else {
    showToast('📸 html2canvas not loaded - screenshot simulated');
    AppState.feedbackScreenshot = 'simulated';
    const preview = document.getElementById('fb-screenshot-preview');
    if (preview) {
      preview.innerHTML = `<div style="padding:20px; background:var(--gray-100); border-radius:8px; text-align:center; color:var(--gray-500);">📸 Screenshot would be captured here<br><span style="font-size:11px;">(html2canvas CDN needed for actual screenshots)</span></div>`;
    }
  }
}

function submitFeedback() {
  const type = document.getElementById('fb-type')?.value || 'other';
  const comment = document.getElementById('fb-comment')?.value || '';

  if (!comment.trim()) {
    showToast('Please add a comment');
    return;
  }

  const feedback = {
    screen: AppState.currentScreen,
    role: AppState.role,
    type: type,
    comment: comment,
    screenshot: AppState.feedbackScreenshot ? 'attached' : 'none',
    timestamp: new Date().toISOString(),
    viewport: `${window.innerWidth}x${window.innerHeight}`,
    userAgent: navigator.userAgent
  };

  // In production, this would create a GitHub issue
  // For prototype, we just show success
  console.log('Feedback submitted:', feedback);

  if (GITHUB_TOKEN !== 'your_token_here') {
    // Real GitHub API call
    createGitHubIssue(feedback);
  } else {
    // Simulated submission
    closeModal();
    showToast('✅ Feedback submitted! (Simulated - set GitHub token for real submission)');
    AppState.feedbackScreenshot = null;
  }
}

async function createGitHubIssue(feedback) {
  try {
    const title = `[${feedback.type}] ${feedback.screen} — ${feedback.comment.substring(0, 60)}`;
    const body = `## Feedback\n\n**Screen:** ${feedback.screen}\n**Role:** ${feedback.role}\n**Type:** ${feedback.type}\n**Viewport:** ${feedback.viewport}\n**Time:** ${feedback.timestamp}\n\n### Comment\n${feedback.comment}\n\n### Screenshot\n${feedback.screenshot === 'attached' ? '(Screenshot attached below)' : 'No screenshot'}\n\n---\n*Auto-generated by ShopSaathi Feedback Widget*`;

    const response = await fetch(`https://api.github.com/repos/${GITHUB_REPO}/issues`, {
      method: 'POST',
      headers: {
        'Authorization': `token ${GITHUB_TOKEN}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        title: title,
        body: body,
        labels: ['feedback', feedback.type]
      })
    });

    if (response.ok) {
      closeModal();
      showToast('✅ GitHub Issue created!');
    } else {
      showToast('❌ Failed to create issue');
    }
  } catch (err) {
    showToast('❌ Network error');
    console.error('GitHub API error:', err);
  }

  AppState.feedbackScreenshot = null;
}
